# Configuration file for the application
# This file contains settings for the application, such as window size and fullscreen mode.

test mode: OpenGL
window_width: 800
window_height: 600
fullscreen: false
vertex_Shader_file: ../../../resources/vertexShader.glsl
fragment_Shader_file: ../../../resources/fragmentShader.glsl

#Camera settings
camera_position: [0.0, 0.0, 3.0]
camera_fov: 45.0
camera_aspect_ratio: -1
camera_near_plane: 0.1
camera_far_plane: 10.0
background_color: [0.2, 0.2, 0.2]